header_pages:
  - index.md
  - rules.md
  - student1.md
  - contact.md

remote_theme: b2a3e8/jekyll-theme-console
style: dark # dark (default), light or hacker
footer: 'WOCSHACK by <a href="https://wocsa.org">WOCSA</a>'
